# basic MCSTORM on github

name: FlyProxy-MCSTORM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      server_ip_value:
        description: 'IP of server FlyProxy-MCSTORM.'
        required: true
        default: 'IP'
        type: string
      server_port_value:
        description: 'PORT of FlyProxy-MCSTORM.'
        required: true
        default: 'PORT'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run FlyPingawith github actions. ggs if server doesnt have bungee lol:)
        run: |
          timeout 60s java -jar FlyPing.jar host-${{ github.event.inputs.server_ip_value }} port-${{ github.event.inputs.server_port_value }} threads-1000
    env:
      server_ip: ${{ github.event.inputs.server_ip_value }}
      server_port: ${{ github.event.inputs.server_port_value }}
